gestures:
  0: "turn_off"      # Tắt tất cả đèn / Không có cử chỉ
  1: "light1_on"     # Bật đèn số 1
  2: "light1_off"    # Tắt đèn số 1  
  3: "light2_on"     # Bật đèn số 2
  4: "light2_off"    # Tắt đèn số 2
  5: "turn_on"       # Cử chỉ OK 

# Cấu hình cảm biến
sensor_settings:
  max_hands: 1
  detection_confidence: 0.7
  tracking_confidence: 0.5


Dataset:
  train: 'E:\AIO2025\gesture_recognization\data\landmarks_train.csv'
  val: 'E:\AIO2025\gesture_recognization\data\landmarks_val.csv'
  test: 'E:\AIO2025\gesture_recognization\data\landmarks_test.csv'

